services:

  neuronytest:
    container_name: neuronytest
    build: .
    volumes:
      - ./:/var/www/html
    ports:
      - 1000:80

  node:
    container_name: node
    build:
      context: .
      dockerfile: Dockerfile.node
    image: node:latest
    ports:
      - 1001:3000
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - /var/www/html/node_modules

  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 1306:3306

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    restart: always
    ports:
      - 1301:80
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: secret
    links:
      - mysql