# Set the base image
FROM node:latest

# Set working directory
WORKDIR /var/www/html

# Copy `package.json` and `package-lock.json`
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy project files into the docker image
COPY . .

# Expose the port Vite runs on
EXPOSE 1001

# Start the Vite server
CMD ["npm", "run", "dev"]